import { COMMON_APP_FORM_TYPES } from '@dc/screens/UserApp/CommonApp/CommonAppRequests/types';

export const UNSUBMITABLE_FORMS = [
  COMMON_APP_FORM_TYPES.COUNSELOR_FEE_WAIVER,
  COMMON_APP_FORM_TYPES.COUNSELOR_EARLY_DECISION,
  COMMON_APP_FORM_TYPES.COUNSELOR_EARLY_DECISION_2,
];

export const MEMBER_SPECIFIC_FORMS = [
  COMMON_APP_FORM_TYPES.COUNSELOR_FINAL_REPORT,
  COMMON_APP_FORM_TYPES.COUNSELOR_EARLY_DECISION,
  COMMON_APP_FORM_TYPES.COUNSELOR_EARLY_DECISION_2,
];
