import { RJSFSchema, UiSchema } from '@rjsf/utils';

import { CommonAppRawQuestions } from '../forms';

export const teacherQuestionsSchema: RJSFSchema = {
  type: 'object',
  $defs: {},
  properties: {
    '1388': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Dr.',
        },
        {
          const: 1,
          title: 'Mr.',
        },
        {
          const: 2,
          title: 'Ms.',
        },
        {
          const: 3,
          title: 'Mrs.',
        },
        {
          const: 4,
          title: 'Mx.',
        },
        {
          const: 5,
          title: 'Other',
        },
      ],
      title: 'Prefix',
      $id: '1388',
    },
    '1389': {
      type: 'string',
      title: 'First name',
      $id: '1389',
      maxLength: 30,
    },
    '1390': {
      type: 'string',
      title: 'Middle initial',
      $id: '1390',
      maxLength: 2,
    },
    '1391': {
      type: 'string',
      title: 'Last name',
      $id: '1391',
      maxLength: 30,
    },
    '1392': {
      type: 'string',
      title: 'Title',
      $id: '1392',
      maxLength: 60,
    },
    '1393': {
      type: 'string',
      title: 'Phone',
      $id: '1393',
    },
    '1394': {
      type: 'string',
      title: 'Fax',
      $id: '1394',
    },
    '1395': {
      type: 'string',
      format: 'email',
      title: 'Email',
      $id: '1395',
    },
    '1397': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title:
        "Do you complete applicants' academic ratings on the Common Application Teacher Evaluation?",
      $id: '1397',
    },
    '1909': {
      type: 'number',
      oneOf: [
        {
          const: 1,
          title: 'High school/secondary school teacher',
        },
        {
          const: 2,
          title: 'College/university instructor',
        },
      ],
      title:
        'Please indicate if you are a high school/secondary school teacher or a college/university instructor',
      $id: '1909',
    },
    'Personal Details': {
      type: 'object',
      properties: {},
    },
    'School Details': {
      type: 'object',
      properties: {},
    },
  },
  required: ['1389', '1391', '1392', '1393', '1395', '1397', '1909'],
  allOf: [
    {
      if: {
        properties: {
          '1909': {
            const: 1,
          },
        },
      },
      then: {
        properties: {
          '1396': {
            type: 'string',
            pattern: '^[0-9]{6}$',
            title: 'High School CEEB code',
            $id: '1396',
            minLength: 6,
            maxLength: 6,
          },
        },
        required: ['1396'],
      },
    },
    {
      if: {
        properties: {
          '1909': {
            const: 2,
          },
        },
      },
      then: {
        properties: {
          '1910': {
            type: 'string',
            pattern: '^[0-9]{4}$',
            title: 'College CEEB code',
            $id: '1910',
            minLength: 4,
            maxLength: 4,
          },
        },
        required: ['1910'],
      },
    },
    {
      if: {
        properties: {
          '1388': {
            const: 5,
          },
        },
      },
      then: {
        properties: {
          '2066': {
            type: 'string',
            title: 'Other prefix',
            $id: '2066',
            maxLength: 24,
          },
        },
        required: ['2066'],
      },
    },
  ],
};

export const teacherQuestionsUISchema: { [key: string]: UiSchema } = {
  '1393': {
    'ui:widget': 'PhoneWidget',
  },
  '1394': {
    'ui:widget': 'PhoneWidget',
  },
  '1397': {
    'ui:widget': 'radio',
  },
  '1909': {
    'ui:widget': 'radio',
  },
  'ui:order': [
    'Personal Details',
    '1388',
    '2066',
    '1389',
    '1390',
    '1391',
    '1392',
    '1393',
    '1394',
    '1395',
    'School Details',
    '1909',
    '1396',
    '1910',
    '1397',
  ],
};

export const teacherProfileRawQuestions: CommonAppRawQuestions = {
  '1388': {
    sectionName: 'Personal Details',
    id: '1388',
    label: 'Prefix',
    type: 'SingleSelectDropdown',
    name: 'Teacher title',
    format: null,
    choiceGroup: 'Prefix',
    orderSeq: '10',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1389': {
    sectionName: 'Personal Details',
    id: '1389',
    label: 'First name',
    type: 'Short',
    name: 'Teacher first name',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1390': {
    sectionName: 'Personal Details',
    id: '1390',
    label: 'Middle initial',
    type: 'Short',
    name: 'Teacher MI',
    format: null,
    choiceGroup: null,
    orderSeq: '30',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '2',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1391': {
    sectionName: 'Personal Details',
    id: '1391',
    label: 'Last name',
    type: 'Short',
    name: 'Teacher last name',
    format: null,
    choiceGroup: null,
    orderSeq: '40',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1392': {
    sectionName: 'Personal Details',
    id: '1392',
    label: 'Title',
    type: 'Short',
    name: 'Teacher position',
    format: null,
    choiceGroup: null,
    orderSeq: '50',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '60',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1393': {
    sectionName: 'Personal Details',
    id: '1393',
    label: 'Phone',
    type: 'Phone',
    name: 'Teacher phone',
    format: 'Phone Validations',
    choiceGroup: null,
    orderSeq: '60',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1394': {
    sectionName: 'Personal Details',
    id: '1394',
    label: 'Fax',
    type: 'Phone',
    name: 'Teacher fax',
    format: 'Phone Validations',
    choiceGroup: null,
    orderSeq: '70',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1395': {
    sectionName: 'Personal Details',
    id: '1395',
    label: 'Email',
    type: 'Email',
    name: 'Teacher email',
    format: "(must include '@' in response)",
    choiceGroup: null,
    orderSeq: '80',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1396': {
    sectionName: 'School Details',
    id: '1396',
    label: 'High School CEEB code',
    type: '6 digit High School CEEB code',
    name: 'Teacher School lookup',
    format: '######',
    choiceGroup: null,
    orderSeq: '10',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'is high school teacher',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1397': {
    sectionName: 'School Details',
    id: '1397',
    label:
      "Do you complete applicants' academic ratings on the Common Application Teacher Evaluation?",
    type: 'Radio',
    name: 'Teacher Academic ratings',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '20',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1909': {
    sectionName: 'School Details',
    id: '1909',
    label:
      'Please indicate if you are a high school/secondary school teacher or a college/university instructor',
    type: 'Radio',
    name: 'Instructor type',
    format: null,
    choiceGroup: 'High School Teacher or College Instructor',
    orderSeq: '5',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1910': {
    sectionName: 'School Details',
    id: '1910',
    label: 'College CEEB code',
    type: '4 digit College CEEB code',
    name: 'Teacher College lookup',
    format: '####',
    choiceGroup: null,
    orderSeq: '15',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'is college instructor',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '2066': {
    sectionName: 'Personal Details',
    id: '2066',
    label: 'Other prefix',
    type: 'Short',
    name: 'Teacher Other Prefix',
    format: null,
    choiceGroup: null,
    orderSeq: '15',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Teacher Other Prefix rule',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '24',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
};

export const teacherQuestionsInitialData = {
  '1388': null, // Prefix - condition depends on it
  '1909': null, // Condition - depends on it
};
