export enum SUBMISSION_STATUS {
  NOT_STARTED = 'NOT_STARTED',
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  ACCEPTED = 'ACCEPTED',
  GRADED = 'GRADED',
  NOT_ACCEPTED = 'NOT_ACCEPTED',
  // type for FE usage!
  RE_SUBMITTED = 'RE_SUBMITTED',
  UPDATED = 'UPDATED',
}
