import { STATEMENT_QUESTION_TYPE } from '@shared/resources/enums';

export const QUESTION_TYPES_WITH_OPTIONS = [
  STATEMENT_QUESTION_TYPE.MULTIPLE_CHOICE,
  STATEMENT_QUESTION_TYPE.MULTIPLE_CHOICE_DROPDOWN,
  STATEMENT_QUESTION_TYPE.SINGLE_CHOICE,
];
