import { RJSFSchema } from '@rjsf/utils';

import { CommonAppRawQuestions } from '../forms';

//INFO :   '1285': null,
// '1741': null,
// '1294': null,
// added those initila values
// MISSING HOME SCHOOLINIG QUESTIONS

export const schoolReportSchema: RJSFSchema = {
  type: 'object',
  $defs: {},
  properties: {
    '1050': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title: 'Is the applicant an Advanced Cambridge (AICE) Diploma Candidate?',
      $id: '1050',
    },
    '1055': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title: 'Is the applicant an AP Capstone Diploma candidate?',
      $id: '1055',
    },
    '1252': {
      type: 'number',
      oneOf: [
        {
          const: 1,
          title: 'Exact',
        },
        {
          const: 2,
          title: 'Decile',
        },
        {
          const: 3,
          title: 'Quintile',
        },
        {
          const: 4,
          title: 'Quartile',
        },
        {
          const: 5,
          title: 'None',
        },
      ],
      title: 'How do you report class rank?',
      $id: '1252',
    },
    '1261': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title: 'Do you report GPA (Grade Point Average)?',
      $id: '1261',
    },
    '1269': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Less than demanding',
        },
        {
          const: 1,
          title: 'Average',
        },
        {
          const: 2,
          title: 'Demanding',
        },
        {
          const: 3,
          title: 'Very demanding',
        },
        {
          const: 4,
          title: 'Most demanding',
        },
        {
          const: 5,
          title: 'Prefer not to respond',
        },
      ],
      title:
        "In comparison with other college preparatory students at your school, the applicant's course selection is",
      $id: '1269',
    },
    '1270': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title: 'Is the applicant an IB Diploma Candidate?',
      $id: '1270',
    },
    '1285': {
      type: 'number',
      oneOf: [
        {
          const: 1,
          title: '1',
        },
        {
          const: 2,
          title: '2',
        },
        {
          const: 3,
          title: '3',
        },
        {
          const: 4,
          title: '4',
        },
      ],
      title: 'Please indicate number of official transcripts you can provide for the applicant.',
      $id: '1285',
    },
    '1741': {
      type: 'number',
      oneOf: [
        {
          const: 1,
          title: 'No basis',
        },
        {
          const: 2,
          title: 'With reservation',
        },
        {
          const: 3,
          title: 'Fairly strongly',
        },
        {
          const: 4,
          title: 'Strongly',
        },
        {
          const: 5,
          title: 'Enthusiastically',
        },
      ],
      title: 'I recommend this student:',
      $id: '1741',
    },
    Curriculum: {
      type: 'object',
      properties: {},
    },
    'Class Rank': {
      type: 'object',
      properties: {},
    },
    GPA: {
      type: 'object',
      properties: {},
    },
    Transcripts: {
      type: 'object',
      properties: {},
    },
    // 'Home School': {
    //   type: 'object',
    //   properties: {},
    // },
  },
  required: ['1050', '1055', '1252', '1261', '1269', '1270', '1285', '1741'],
  allOf: [
    {
      if: {
        properties: {
          '1252': {
            anyOf: [{ const: 1 }, { const: 2 }, { const: 3 }, { const: 4 }],
          },
        },
      },
      then: {
        properties: {
          '1258': {
            type: 'number',
            oneOf: [
              {
                const: 1,
                title: 'Weighted',
              },
              {
                const: 2,
                title: 'Unweighted',
              },
            ],
            title: 'Rank weighting',
            $id: '1258',
          },
          '1259': {
            type: 'string',
            format: 'date',
            title: 'From (start date)',
            $id: '1259',
          },
          '1260': {
            type: 'string',
            format: 'date',
            title: 'Ending (final date)',
            $id: '1260',
          },
        },
        required: ['1258', '1259', '1260'],
      },
    },
    {
      if: {
        properties: {
          '1252': {
            const: 1,
          },
        },
      },
      then: {
        properties: {
          '1253': {
            type: 'integer',
            title: "Applicant's class rank",
            $id: '1253',
            maxLength: 5,
          },
          '1254': {
            type: 'integer',
            title: 'How many additional students share this rank?',
            $id: '1254',
            maxLength: 5,
          },
        },
        required: ['1253', '1254'],
      },
    },
    {
      if: {
        properties: {
          '1252': {
            const: 2,
          },
        },
      },
      then: {
        properties: {
          '1255': {
            type: 'number',
            oneOf: [
              {
                const: 1,
                title: 'Top 10%',
              },
              {
                const: 2,
                title: 'Top 20%',
              },
              {
                const: 3,
                title: 'Top 30%',
              },
              {
                const: 4,
                title: 'Top 40%',
              },
              {
                const: 5,
                title: 'Top 50%',
              },
              {
                const: 6,
                title: 'Top 60%',
              },
              {
                const: 7,
                title: 'Top 70%',
              },
              {
                const: 8,
                title: 'Top 80%',
              },
              {
                const: 9,
                title: 'Top 90%',
              },
              {
                const: 10,
                title: 'Top 100%',
              },
            ],
            title: "Applicant's decile rank",
            $id: '1255',
          },
        },
        required: ['1255'],
      },
    },
    {
      if: {
        properties: {
          '1252': {
            const: 3,
          },
        },
      },
      then: {
        properties: {
          '1256': {
            type: 'number',
            oneOf: [
              {
                const: 1,
                title: 'Top 20%',
              },
              {
                const: 2,
                title: 'Top 40%',
              },
              {
                const: 3,
                title: 'Top 60%',
              },
              {
                const: 4,
                title: 'Top 80%',
              },
              {
                const: 5,
                title: 'Top 100%',
              },
            ],
            title: "Applicant's quintile rank",
            $id: '1256',
          },
        },
        required: ['1256'],
      },
    },
    {
      if: {
        properties: {
          '1252': {
            const: 4,
          },
        },
      },
      then: {
        properties: {
          '1257': {
            type: 'number',
            oneOf: [
              {
                const: 1,
                title: 'Top 25%',
              },
              {
                const: 2,
                title: 'Top 50%',
              },
              {
                const: 3,
                title: 'Top 75%',
              },
              {
                const: 4,
                title: 'Top 100%',
              },
            ],
            title: "Applicant's quartile rank",
            $id: '1257',
          },
        },
        required: ['1257'],
      },
    },
    {
      if: {
        properties: {
          '1261': {
            const: 0,
          },
        },
      },
      then: {
        properties: {
          '1262': {
            type: 'number',
            title: 'Cumulative GPA',
            $id: '1262',
            maxLength: 6,
          },
          '1263': {
            type: 'number',
            oneOf: [
              {
                const: 4,
                title: '4',
              },
              {
                const: 5,
                title: '5',
              },
              {
                const: 6,
                title: '6',
              },
              {
                const: 7,
                title: '7',
              },
              {
                const: 8,
                title: '8',
              },
              {
                const: 9,
                title: '9',
              },
              {
                const: 10,
                title: '10',
              },
              {
                const: 11,
                title: '11',
              },
              {
                const: 12,
                title: '12',
              },
              {
                const: 13,
                title: '13',
              },
              {
                const: 14,
                title: '14',
              },
              {
                const: 15,
                title: '15',
              },
              {
                const: 16,
                title: '16',
              },
              {
                const: 17,
                title: '17',
              },
              {
                const: 18,
                title: '18',
              },
              {
                const: 19,
                title: '19',
              },
              {
                const: 20,
                title: '20',
              },
              {
                const: 100,
                title: '100',
              },
            ],
            title: 'GPA Scale',
            $id: '1263',
          },
          '1264': {
            type: 'string',
            format: 'date',
            title: 'From (start date)',
            $id: '1264',
          },
          '1265': {
            type: 'string',
            format: 'date',
            title: 'Ending (final date)',
            $id: '1265',
          },
          '1266': {
            type: 'number',
            oneOf: [
              {
                const: 1,
                title: 'Weighted',
              },
              {
                const: 2,
                title: 'Unweighted',
              },
            ],
            title: 'GPA weighting',
            $id: '1266',
          },
          '1267': {
            type: 'string',
            title: "School's passing mark",
            $id: '1267',
            maxLength: 6,
          },
          '1268': {
            type: 'string',
            title: 'Highest grade/GPA in class',
            $id: '1268',
            maxLength: 6,
          },
        },
        required: ['1262', '1263', '1264', '1265', '1266', '1267'],
      },
    },
    {
      if: {
        properties: {
          '1247': {
            const: 0,
          },
        },
      },
      then: {
        properties: {
          Ratings: {
            type: 'object',
            properties: {},
          },
          '1271': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title:
              'Compared to other students in his or her class, how do you rate this applicant in terms of academic achievements.',
            $id: '1271',
          },
          '1272': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title:
              'Compared to other students in his or her class, how do you rate this applicant in terms of extracurricular accomplishments.',
            $id: '1272',
          },
          '1273': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title:
              'Compared to other students in his or her class, how do you rate this applicant in terms of personal qualities and character.',
            $id: '1273',
          },
          '1274': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title:
              'Compared to other students in his or her class, how do you rate this applicant overall.',
            $id: '1274',
          },
        },
        required: ['1271', '1272', '1273', '1274'],
      },
    },
    {
      if: {
        properties: {
          '1285': {
            anyOf: [
              {
                const: 1,
              },
              {
                const: 2,
              },
              {
                const: 3,
              },
              {
                const: 4,
              },
            ],
          },
        },
      },
      then: {
        properties: {
          '1286': {
            type: 'string',
            format: 'data-url',
            title: 'Current or most recent transcript',
            $id: '1286',
          },
          '1290': {
            type: 'array',
            uniqueItems: true,
            items: {
              type: 'number',
              anyOf: [
                {
                  const: 0,
                  title:
                    'I affirm that I have uploaded a transcript to this School Report. I understand that failure to do so (by, for example, uploading a blank document or uploading a document promising to mail the transcript at a later time) will result in my Common App Online account being closed.',
                },
              ],
            },
            title: 'Transcript Affirmation',
            $id: '1290',
          },
          '1291': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'Final junior year grades',
              },
              {
                const: 1,
                title: '1st Quarter senior year grades',
              },
              {
                const: 2,
                title: '2nd Quarter/1st Semester senior year grades',
              },
              {
                const: 3,
                title: '3rd Quarter senior year grades',
              },
              {
                const: 4,
                title: '1st Trimester senior year grades',
              },
              {
                const: 5,
                title: '2nd Trimester senior year grades',
              },
              {
                const: 6,
                title: 'Final senior year grades',
              },
            ],
            title:
              'Please indicate the most recent grades included on the transcript accompanying this form',
            $id: '1291',
          },
          '1796': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'Yes',
              },
              {
                const: 1,
                title: 'No',
              },
            ],
            title: 'Are current courses listed on the transcript?',
            $id: '1796',
          },
          '1830': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'Yes',
              },
              {
                const: 1,
                title: 'No',
              },
            ],
            title:
              'Are college entrance examination scores included with or visible on the transcript?',
            $id: '1830',
          },
        },
        required: ['1286', '1290', '1291', '1796', '1830'],
      },
    },
    {
      if: {
        properties: {
          '1285': {
            anyOf: [
              {
                const: 2,
              },
              {
                const: 3,
              },
              {
                const: 4,
              },
            ],
          },
        },
      },
      then: {
        properties: {
          '1287': {
            type: 'string',
            format: 'data-url',
            title: 'Additional transcript',
            $id: '1287',
          },
        },
        required: ['1287'],
      },
    },
    {
      if: {
        properties: {
          '1285': {
            anyOf: [
              {
                const: 3,
              },
              {
                const: 4,
              },
            ],
          },
        },
      },
      then: {
        properties: {
          '1288': {
            type: 'string',
            format: 'data-url',
            title: 'Additional transcript',
            $id: '1288',
          },
        },
        required: ['1288'],
      },
    },
    {
      if: {
        properties: {
          '1285': {
            const: 4,
          },
        },
      },
      then: {
        properties: {
          '1289': {
            type: 'string',
            format: 'data-url',
            title: 'Additional transcript',
            $id: '1289',
          },
        },
        required: ['1289'],
      },
    },
    {
      if: {
        properties: {
          '1246': {
            const: 1,
          },
        },
      },
      then: {
        properties: {
          'International School': {
            type: 'object',
            properties: {},
          },
          '1292': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'Albanian',
              },
              {
                const: 1,
                title: 'Arabic',
              },
              {
                const: 2,
                title: 'Armenian',
              },
              {
                const: 3,
                title: 'Assamese',
              },
              {
                const: 4,
                title: 'Azerbaijani',
              },
              {
                const: 5,
                title: 'Belarusian',
              },
              {
                const: 6,
                title: 'Bengali',
              },
              {
                const: 7,
                title: 'Bulgarian',
              },
              {
                const: 8,
                title: 'Catalan/Valencian',
              },
              {
                const: 9,
                title: 'Chinese',
              },
              {
                const: 10,
                title: 'Croatian',
              },
              {
                const: 11,
                title: 'Czech',
              },
              {
                const: 12,
                title: 'Danish',
              },
              {
                const: 13,
                title: 'Dutch/Flemish',
              },
              {
                const: 14,
                title: 'English',
              },
              {
                const: 15,
                title: 'Estonian',
              },
              {
                const: 16,
                title: 'Finnish',
              },
              {
                const: 17,
                title: 'French',
              },
              {
                const: 18,
                title: 'Georgian',
              },
              {
                const: 19,
                title: 'German',
              },
              {
                const: 20,
                title: 'Greek',
              },
              {
                const: 21,
                title: 'Gujarati',
              },
              {
                const: 22,
                title: 'Hebrew',
              },
              {
                const: 23,
                title: 'Hindi',
              },
              {
                const: 24,
                title: 'Hungarian',
              },
              {
                const: 25,
                title: 'Icelandic',
              },
              {
                const: 26,
                title: 'Italian',
              },
              {
                const: 27,
                title: 'Japanese',
              },
              {
                const: 28,
                title: 'Javanese',
              },
              {
                const: 29,
                title: 'Korean',
              },
              {
                const: 30,
                title: 'Latvian',
              },
              {
                const: 31,
                title: 'Lithuanian',
              },
              {
                const: 32,
                title: 'Macedonian',
              },
              {
                const: 33,
                title: 'Malay',
              },
              {
                const: 34,
                title: 'Malayalam',
              },
              {
                const: 35,
                title: 'Marathi',
              },
              {
                const: 36,
                title: 'Moldavian',
              },
              {
                const: 37,
                title: 'Norwegian',
              },
              {
                const: 38,
                title: 'Other',
              },
              {
                const: 39,
                title: 'Persian',
              },
              {
                const: 40,
                title: 'Polish',
              },
              {
                const: 41,
                title: 'Portuguese',
              },
              {
                const: 42,
                title: 'Romanian',
              },
              {
                const: 43,
                title: 'Russian',
              },
              {
                const: 44,
                title: 'Serbian',
              },
              {
                const: 45,
                title: 'Slovak',
              },
              {
                const: 46,
                title: 'Slovenian',
              },
              {
                const: 47,
                title: 'Spanish/Castilian',
              },
              {
                const: 48,
                title: 'Swedish',
              },
              {
                const: 49,
                title: 'Tagalog',
              },
              {
                const: 50,
                title: 'Tamil',
              },
              {
                const: 51,
                title: 'Tatar',
              },
              {
                const: 52,
                title: 'Telugu',
              },
              {
                const: 53,
                title: 'Thai',
              },
              {
                const: 54,
                title: 'Turkish',
              },
              {
                const: 55,
                title: 'Ukrainian',
              },
              {
                const: 56,
                title: 'Urdu',
              },
              {
                const: 57,
                title: 'Vietnamese',
              },
            ],
            title: 'What is the primary language of instruction in your secondary school?',
            $id: '1292',
          },
          '1293': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'Yes',
              },
              {
                const: 1,
                title: 'No',
              },
            ],
            title:
              'International applicants: Is promotion within your educational system based upon standard leaving examinations given at the end of lower and/or senior secondary school by a state or national leaving examinations board? (Students studying in the US typically answer no to this question.)',
            $id: '1293',
          },
          '1736': {
            type: 'string',
            title:
              'Please indicate the marking or grading scale used in your school and its approximate equivalence to the A-F scale commonly used in the United States:<br />A (Excellent)',
            $id: '1736',
            maxLength: 30,
          },
          '1737': {
            type: 'string',
            title: 'B (Very Good)',
            $id: '1737',
            maxLength: 30,
          },
          '1738': {
            type: 'string',
            title: 'C (Average)',
            $id: '1738',
            maxLength: 30,
          },
          '1739': {
            type: 'string',
            title: 'D (Poor)',
            $id: '1739',
            maxLength: 30,
          },
          '1740': {
            type: 'string',
            title: 'F (Failing)',
            $id: '1740',
            maxLength: 30,
          },
        },
        required: ['1292', '1293', '1736', '1737', '1738', '1739', '1740'],
      },
    },
    {
      if: {
        properties: {
          '1293': {
            const: 0,
          },
        },
      },
      then: {
        properties: {
          '1294': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'Yes',
              },
              {
                const: 1,
                title: 'No',
              },
            ],
            title: 'Has applicant already taken leaving exams?',
            $id: '1294',
          },
        },
        required: ['1294'],
      },
    },
    {
      if: {
        properties: {
          '1294': {
            const: 0,
          },
        },
      },
      then: {
        properties: {
          '1295': {
            type: 'string',
            format: 'data-url',
            title:
              "Please upload an official copy of this student's lower secondary examination results. If the student has already taken senior secondary leaving exams, please include an official copy of the results. If this applicant's senior secondary leaving exam results are not yet available, please indicate predicted results.",
            $id: '1295',
          },
        },
        required: ['1295'],
      },
    },
    // {
    //   if: {
    //     properties: {
    //       '1299': {
    //         const: 0,
    //       },
    //     },
    //   },
    //   then: {
    //     properties: {
    //       '1300': {
    //         type: 'string',
    //         title: 'Association name',
    //         $id: '1300',
    //         maxLength: 60,
    //       },
    //     },
    //     required: ['1300'],
    //   },
    // },
    {
      if: {
        properties: {
          '1796': {
            const: 1,
          },
        },
      },
      then: {
        properties: {
          '1797': {
            type: 'string',
            format: 'data-url',
            title: 'Please upload a document which lists the current courses for this student.',
            $id: '1797',
          },
        },
        required: ['1797'],
      },
    },
  ],
};

export const schoolReportUiSchema = {
  '1050': {
    'ui:widget': 'radio',
  },
  '1055': {
    'ui:widget': 'radio',
  },
  '1258': {
    'ui:widget': 'radio',
  },
  '1259': {
    'ui:options': {
      yearsRange: ['1952', '2028'],
    },
    'ui:widget': 'MonthYearWidget',
  },
  '1260': {
    'ui:options': {
      yearsRange: ['1952', '2028'],
    },
    'ui:widget': 'MonthYearWidget',
  },
  '1261': {
    'ui:widget': 'radio',
  },
  '1264': {
    'ui:options': {
      yearsRange: ['1952', '2028'],
    },
    'ui:widget': 'MonthYearWidget',
  },
  '1265': {
    'ui:options': {
      yearsRange: ['1952', '2028'],
    },
    'ui:widget': 'MonthYearWidget',
  },
  '1266': {
    'ui:widget': 'radio',
  },
  '1270': {
    'ui:widget': 'radio',
  },
  '1271': {
    'ui:widget': 'radio',
  },
  '1272': {
    'ui:widget': 'radio',
  },
  '1273': {
    'ui:widget': 'radio',
  },
  '1274': {
    'ui:widget': 'radio',
  },
  '1286': {
    'ui:options': {
      accept: '.pdf',
    },
  },
  '1287': {
    'ui:options': {
      accept: '.pdf',
    },
  },
  '1288': {
    'ui:options': {
      accept: '.pdf',
    },
  },
  '1289': {
    'ui:options': {
      accept: '.pdf',
    },
  },
  '1290': {
    'ui:widget': 'checkboxes',
  },
  '1293': {
    'ui:widget': 'radio',
  },
  '1294': {
    'ui:widget': 'radio',
  },
  '1295': {
    'ui:options': {
      accept: '.pdf',
    },
  },
  '1296': {
    'ui:widget': 'textarea',
  },
  '1297': {
    'ui:widget': 'textarea',
  },
  '1298': {
    'ui:widget': 'textarea',
  },
  '1299': {
    'ui:widget': 'radio',
  },
  '1741': {
    'ui:widget': 'radio',
  },
  '1797': {
    'ui:options': {
      accept: '.pdf',
    },
  },
  'ui:order': [
    'Curriculum',
    '1247',
    '1269',
    '1270',
    '1050',
    '1055',
    'Class Rank',
    '1252',
    '1253',
    '1254',
    '1255',
    '1256',
    '1257',
    '1258',
    '1259',
    '1260',
    'GPA',
    '1261',
    '1262',
    '1263',
    '1264',
    '1265',
    '1266',
    '1267',
    '1268',
    'Ratings',
    '1271',
    '1272',
    '1273',
    '1274',
    'Transcripts',
    '1285',
    '1286',
    '1796',
    '1830',
    '1797',
    '1287',
    '1288',
    '1289',
    '1290',
    '1291',
    '1741',
    'International School',
    '1292',
    '1293',
    '1294',
    '1295',
    '1736',
    '1737',
    '1738',
    '1739',
    '1740',
    'Home School',
    '1296',
    '1297',
    '1298',
    '1299',
    '1300',
  ],
};

export const srInitialValues = {
  '1252': '',
  '1261': '',
  '1796': '',
  '1285': null,
  '1293': null,
  '1294': null,
};

// raw questions data in case we need it

export const schoolReportRawQuestions: CommonAppRawQuestions = {
  '1050': {
    sectionName: 'Curriculum',
    id: '1050',
    label: 'Is the applicant an Advanced Cambridge (AICE) Diploma Candidate?',
    type: 'Radio',
    name: 'SR AICE Diploma candidate',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '30',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1055': {
    sectionName: 'Curriculum',
    id: '1055',
    label: 'Is the applicant an AP Capstone Diploma candidate?',
    type: 'Radio',
    name: 'SR AP Capstone Diploma candidate',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '40',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1252': {
    sectionName: 'Class Rank',
    id: '1252',
    label: 'How do you report class rank?',
    type: 'SingleSelectDropdown',
    name: 'SR Class Rank reporting',
    format: null,
    choiceGroup: 'Class Rank reporting',
    orderSeq: '10',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1253': {
    sectionName: 'Class Rank',
    id: '1253',
    label: "Applicant's class rank",
    type: 'Short',
    name: 'SR Exact Class rank',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Exact class rank display',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1254': {
    sectionName: 'Class Rank',
    id: '1254',
    label: 'How many additional students share this rank?',
    type: 'Short',
    name: 'SR Students Sharing Rank',
    format: null,
    choiceGroup: null,
    orderSeq: '30',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Exact class rank display',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1255': {
    sectionName: 'Class Rank',
    id: '1255',
    label: "Applicant's decile rank",
    type: 'SingleSelectDropdown',
    name: 'SR Decile Rank',
    format: null,
    choiceGroup: 'Decile rank',
    orderSeq: '40',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Decile rank display',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1256': {
    sectionName: 'Class Rank',
    id: '1256',
    label: "Applicant's quintile rank",
    type: 'SingleSelectDropdown',
    name: 'SR Quintile Rank',
    format: null,
    choiceGroup: 'Quintile rank',
    orderSeq: '50',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Quintile rank display',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1257': {
    sectionName: 'Class Rank',
    id: '1257',
    label: "Applicant's quartile rank",
    type: 'SingleSelectDropdown',
    name: 'SR Quartile Rank',
    format: null,
    choiceGroup: 'Quartile Rank',
    orderSeq: '60',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Quartile rank display',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1258': {
    sectionName: 'Class Rank',
    id: '1258',
    label: 'Rank weighting',
    type: 'Radio',
    name: 'SR Rank weighting',
    format: null,
    choiceGroup: 'Weighting',
    orderSeq: '70',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Rank weighting display',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1259': {
    sectionName: 'Class Rank',
    id: '1259',
    label: 'From (start date)',
    type: 'Month (MM/YYYY)',
    name: 'SR Class rank start date',
    format: null,
    choiceGroup: null,
    orderSeq: '80',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Rank weighting display',
    dataType: 'Date',
    minWordsYear: '1952',
    maxWordsYearKb: '2028',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation:
      'From (start date) must be earlier than Ending (final date). Please correct them.',
  },
  '1260': {
    sectionName: 'Class Rank',
    id: '1260',
    label: 'Ending (final date)',
    type: 'Month (MM/YYYY)',
    name: 'SR Class rank end date',
    format: null,
    choiceGroup: null,
    orderSeq: '90',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Rank weighting display',
    dataType: 'Date',
    minWordsYear: '1952',
    maxWordsYearKb: '2028',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation:
      'From (start date) must be earlier than Ending (final date). Please correct them.',
  },
  '1261': {
    sectionName: 'GPA',
    id: '1261',
    label: 'Do you report GPA (Grade Point Average)?',
    type: 'Radio',
    name: 'SR GPA Reporting',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '10',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1262': {
    sectionName: 'GPA',
    id: '1262',
    label: 'Cumulative GPA',
    type: 'Short',
    name: 'SR Cumulative GPA',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'GPA details display',
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '6',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1263': {
    sectionName: 'GPA',
    id: '1263',
    label: 'GPA Scale',
    type: 'SingleSelectDropdown',
    name: 'SR GPA Scale',
    format: null,
    choiceGroup: 'REC GPA Scale',
    orderSeq: '30',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'GPA details display',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1264': {
    sectionName: 'GPA',
    id: '1264',
    label: 'From (start date)',
    type: 'Month (MM/YYYY)',
    name: 'SR GPA Start date',
    format: null,
    choiceGroup: null,
    orderSeq: '40',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'GPA details display',
    dataType: 'Date',
    minWordsYear: '1952',
    maxWordsYearKb: '2028',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation:
      'From (start date) must be earlier than Ending (final date). Please correct them.',
  },
  '1265': {
    sectionName: 'GPA',
    id: '1265',
    label: 'Ending (final date)',
    type: 'Month (MM/YYYY)',
    name: 'SR GPA end date',
    format: null,
    choiceGroup: null,
    orderSeq: '50',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'GPA details display',
    dataType: 'Date',
    minWordsYear: '1952',
    maxWordsYearKb: '2028',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation:
      'From (start date) must be earlier than Ending (final date). Please correct them.',
  },
  '1266': {
    sectionName: 'GPA',
    id: '1266',
    label: 'GPA weighting',
    type: 'Radio',
    name: 'SR GPA Weighting',
    format: null,
    choiceGroup: 'Weighting',
    orderSeq: '60',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'GPA details display',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1267': {
    sectionName: 'GPA',
    id: '1267',
    label: "School's passing mark",
    type: 'Short',
    name: 'SR School passing mark',
    format: null,
    choiceGroup: null,
    orderSeq: '70',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'GPA details display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '6',
    allowedCharacters: '[^0-9.A-Za-z]',
    validationPattern: '^([a-zA-Z]+)$|^([0-9]+?.[0-9]+)$|^([0-9]+)$',
    errorMessage:
      'Sorry, we can accept only numbers, decimals and alphabets, please provide a different answer.',
    groupValidation: null,
  },
  '1268': {
    sectionName: 'GPA',
    id: '1268',
    label: 'Highest grade/GPA in class',
    type: 'Short',
    name: 'SR Highest class GPA',
    format: null,
    choiceGroup: null,
    orderSeq: '80',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'GPA details display optional',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '6',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1269': {
    sectionName: 'Curriculum',
    id: '1269',
    label:
      "In comparison with other college preparatory students at your school, the applicant's course selection is",
    type: 'SingleSelectDropdown',
    name: 'SR Course selection',
    format: null,
    choiceGroup: 'Course selection',
    orderSeq: '10',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1270': {
    sectionName: 'Curriculum',
    id: '1270',
    label: 'Is the applicant an IB Diploma Candidate?',
    type: 'Radio',
    name: 'SR IB Diploma candidate',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '20',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1271': {
    sectionName: 'Ratings',
    id: '1271',
    label:
      'Compared to other students in his or her class, how do you rate this applicant in terms of academic achievements.',
    type: 'Radio',
    name: 'SR Rating Academics',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '10',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1272': {
    sectionName: 'Ratings',
    id: '1272',
    label:
      'Compared to other students in his or her class, how do you rate this applicant in terms of extracurricular accomplishments.',
    type: 'Radio',
    name: 'SR Rating Extracurricular',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '20',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1273': {
    sectionName: 'Ratings',
    id: '1273',
    label:
      'Compared to other students in his or her class, how do you rate this applicant in terms of personal qualities and character.',
    type: 'Radio',
    name: 'SR Rating Personal',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '30',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1274': {
    sectionName: 'Ratings',
    id: '1274',
    label:
      'Compared to other students in his or her class, how do you rate this applicant overall.',
    type: 'Radio',
    name: 'SR Rating overall',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '40',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1285': {
    sectionName: 'Transcripts',
    id: '1285',
    label: 'Please indicate number of official transcripts you can provide for the applicant.',
    type: 'SingleSelectDropdown',
    name: 'SR Transcript number',
    format: null,
    choiceGroup: 'Transcript Number',
    orderSeq: '10',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1286': {
    sectionName: 'Transcripts',
    id: '1286',
    label: 'Current or most recent transcript',
    type: 'Upload',
    name: 'SR Transcript 1 upload',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Transcript 1 display',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '2000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1287': {
    sectionName: 'Transcripts',
    id: '1287',
    label: 'Additional transcript',
    type: 'Upload',
    name: 'SR Transcript 2 upload',
    format: null,
    choiceGroup: null,
    orderSeq: '30',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Transcript 2 display',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '2000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1288': {
    sectionName: 'Transcripts',
    id: '1288',
    label: 'Additional transcript',
    type: 'Upload',
    name: 'SR Transcript 3 upload',
    format: null,
    choiceGroup: null,
    orderSeq: '40',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Transcript 3 display',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '2000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1289': {
    sectionName: 'Transcripts',
    id: '1289',
    label: 'Additional transcript',
    type: 'Upload',
    name: 'SR Transcript 4 upload',
    format: null,
    choiceGroup: null,
    orderSeq: '50',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Transcript 4 display',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '2000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1290': {
    sectionName: 'Transcripts',
    id: '1290',
    label: 'Transcript Affirmation',
    type: 'Checkbox',
    name: 'SR Transcript affirmation',
    format: null,
    choiceGroup: 'SR Transcript Affirmation',
    orderSeq: '60',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Transcript 1 display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1291': {
    sectionName: 'Transcripts',
    id: '1291',
    label:
      'Please indicate the most recent grades included on the transcript accompanying this form',
    type: 'SingleSelectDropdown',
    name: 'SR Transcript grades',
    format: null,
    choiceGroup: 'Transcript grade inclusion',
    orderSeq: '70',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Transcript 1 display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1292': {
    sectionName: 'International School',
    id: '1292',
    label: 'What is the primary language of instruction in your secondary school?',
    type: 'SingleSelectDropdown',
    name: 'SR International language',
    format: null,
    choiceGroup: 'Language of instruction',
    orderSeq: '10',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'International questions display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1293': {
    sectionName: 'International School',
    id: '1293',
    label:
      'International applicants: Is promotion within your educational system based upon standard leaving examinations given at the end of lower and/or senior secondary school by a state or national leaving examinations board? (Students studying in the US typically answer no to this question.)',
    type: 'Radio',
    name: 'SR International education',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '20',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'International questions display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1294': {
    sectionName: 'International School',
    id: '1294',
    label: 'Has applicant already taken leaving exams?',
    type: 'Radio',
    name: 'SR International leaving exam',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '30',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Leaving exam display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1295': {
    sectionName: 'International School',
    id: '1295',
    label:
      "Please upload an official copy of this student's lower secondary examination results. If the student has already taken senior secondary leaving exams, please include an official copy of the results. If this applicant's senior secondary leaving exam results are not yet available, please indicate predicted results.",
    type: 'Upload',
    name: 'SR International official results',
    format: null,
    choiceGroup: null,
    orderSeq: '40',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Leaving exam upload display',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '2000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1296': {
    sectionName: 'Home School',
    id: '1296',
    label:
      "Please provide any information about the applicant's homeschool experience and environment that you believe would be helpful to the reader (e.g. educational philosophy, motivation for homeschooling, instruction setting, etc.).",
    type: 'Long',
    name: 'SR Homeschool experience',
    format: null,
    choiceGroup: null,
    orderSeq: '10',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Homeschool required display',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '1000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1297': {
    sectionName: 'Home School',
    id: '1297',
    label: 'Please explain the grading scale or other methods of evaluation.',
    type: 'Long',
    name: 'SR Grading scale',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Homeschool required display',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '1000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1298': {
    sectionName: 'Home School',
    id: '1298',
    label:
      'If the student has taken courses from a distance learning program, traditional secondary school, or college, please list:\n <ul><li>the course title</li>li>content</li><li>sponsoring institution</li><li>instruction setting</li><li>schedule</li><li>frequency of interactions with instructors and other students (once per day, week, etc.)</li></ul>Also include any standardized tests the student has taken that are not listed on the Common App.',
    type: 'Long',
    name: 'SR Outside evaluation',
    format: null,
    choiceGroup: null,
    orderSeq: '30',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'Homeschool optional display',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '1000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1299': {
    sectionName: 'Home School',
    id: '1299',
    label: "Are you a member of a homeschooler's association?",
    type: 'Radio',
    name: 'SR Homeschool association member',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '40',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Homeschool required display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1300': {
    sectionName: 'Home School',
    id: '1300',
    label: 'Association name',
    type: 'Short',
    name: 'SR Homeschool association name',
    format: null,
    choiceGroup: null,
    orderSeq: '50',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Homeschool association question',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '60',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1736': {
    sectionName: 'International School',
    id: '1736',
    label:
      'Please indicate the marking or grading scale used in your school and its approximate equivalence to the A-F scale commonly used in the United States:<br />A (Excellent)',
    type: 'Short',
    name: 'Grading scale Excellent',
    format: null,
    choiceGroup: null,
    orderSeq: '50',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'International questions display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1737': {
    sectionName: 'International School',
    id: '1737',
    label: 'B (Very Good)',
    type: 'Short',
    name: 'Grading scale Very Good',
    format: null,
    choiceGroup: null,
    orderSeq: '60',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'International questions display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1738': {
    sectionName: 'International School',
    id: '1738',
    label: 'C (Average)',
    type: 'Short',
    name: 'Grading scale Average',
    format: null,
    choiceGroup: null,
    orderSeq: '70',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'International questions display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1739': {
    sectionName: 'International School',
    id: '1739',
    label: 'D (Poor)',
    type: 'Short',
    name: 'Grading scale Poor',
    format: null,
    choiceGroup: null,
    orderSeq: '80',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'International questions display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1740': {
    sectionName: 'International School',
    id: '1740',
    label: 'F (Failing)',
    type: 'Short',
    name: 'Grading Scale Failing',
    format: null,
    choiceGroup: null,
    orderSeq: '90',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'International questions display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1741': {
    sectionName: 'Transcripts',
    id: '1741',
    label: 'I recommend this student:',
    type: 'Radio',
    name: 'I recommend this student:',
    format: null,
    choiceGroup: 'Recommendation',
    orderSeq: '80',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1796': {
    sectionName: 'Transcripts',
    id: '1796',
    label: 'Are current courses listed on the transcript?',
    type: 'SingleSelectDropdown',
    name: 'SR Transcript Courses',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '25',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Transcript 1 display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1797': {
    sectionName: 'Transcripts',
    id: '1797',
    label: 'Please upload a document which lists the current courses for this student.',
    type: 'Upload',
    name: 'SR Transcript Courses upload',
    format: null,
    choiceGroup: null,
    orderSeq: '28',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'SR Transcript Courses upload',
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '2000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1830': {
    sectionName: 'Transcripts',
    id: '1830',
    label: 'Are college entrance examination scores included with or visible on the transcript?',
    type: 'SingleSelectDropdown',
    name: 'SR Tests Included',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '26',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Transcript 1 display',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
};
