import { EVIDENCE_CONTEXT_KIND, EVIDENCE_KIND, SERVICE_NAME } from '@shared/resources/enums';

export const automaticallyAddedEvidence = [
  {
    contextType: null,
    label: 'Digital Journalist: The 80s Had Game-Motion Graphics',
    rubricScores: [
      {
        currentScore: 70,
        maxScore: 70,
        label: 'Research',
      },
    ],
    service: SERVICE_NAME.LEARNING,
    type: EVIDENCE_KIND.RUBRIC_GRADE,
    updatedAt: new Date('2023-11-02T14:31:28Z'),
    isTeamSubmission: false,
    id: null,
    itemId: null,
  },
];

export const manuallyAddedEvidence = [
  {
    contextType: null,
    label: 'Motion Graphics DL',
    rubricScores: null,
    service: SERVICE_NAME.LEARNING,
    type: EVIDENCE_KIND.PRODUCT_SUBMISSION,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: false,
    id: '179',
    itemId: '7',
  },
  {
    contextType: null,
    label: 'Motion Graphics DC',
    rubricScores: null,
    service: SERVICE_NAME.CAREERS,
    type: EVIDENCE_KIND.PRODUCT_SUBMISSION,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: false,
    id: '180',
    itemId: '8',
  },
  {
    contextType: EVIDENCE_CONTEXT_KIND.COURSE,
    label: 'Schedule ',
    rubricScores: null,
    service: SERVICE_NAME.CAREERS,
    type: EVIDENCE_KIND.ASSIGNMENT_SUBMISSION,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: false,
    id: '184',
    itemId: '23',
  },
  {
    contextType: EVIDENCE_CONTEXT_KIND.VIRTUAL_INTERNSHIP,
    label: 'Medical Supply Checklist Assignment',
    rubricScores: null,
    service: SERVICE_NAME.CAREERS,
    type: EVIDENCE_KIND.ASSIGNMENT_SUBMISSION,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: false,
    id: '185',
    itemId: '5',
  },
  {
    contextType: null,
    label: 'test :)',
    rubricScores: null,
    service: SERVICE_NAME.CAREERS,
    type: EVIDENCE_KIND.OPPORTUNITY_APPLICATION,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: false,
    id: '183',
    itemId: '16',
  },
  {
    contextType: null,
    label: 'Motion Graphics',
    rubricScores: null,
    service: SERVICE_NAME.LEARNING,
    type: EVIDENCE_KIND.PRODUCT_SUBMISSION,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: false,
    id: '180',
    itemId: '7',
  },
  {
    contextType: null,
    label: 'Family Picture Book',
    rubricScores: null,
    service: SERVICE_NAME.LEARNING,
    type: EVIDENCE_KIND.PRODUCT_SUBMISSION,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: true,
    id: '181',
    itemId: '6',
  },
  {
    contextType: null,
    label: 'Classroom Learning List',
    rubricScores: null,
    service: SERVICE_NAME.LEARNING,
    type: EVIDENCE_KIND.PRODUCT_SUBMISSION,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: false,
    id: '182',
    itemId: '1',
  },
  {
    contextType: null,
    label: 'Bike project',
    rubricScores: null,
    service: SERVICE_NAME.LEARNING,
    type: EVIDENCE_KIND.PORTFOLIO_PROJECT,
    updatedAt: new Date('2023-11-02T12:47:37Z'),
    isTeamSubmission: false,
    id: '186',
    itemId: '4',
  },
];
