import { RJSFSchema } from '@rjsf/utils';

import { CommonAppRawQuestions } from '../forms';

export const counselorProfileSchema: RJSFSchema = {
  type: 'object',
  $defs: {},
  properties: {
    '1210': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Dr.',
        },
        {
          const: 1,
          title: 'Mr.',
        },
        {
          const: 2,
          title: 'Ms.',
        },
        {
          const: 3,
          title: 'Mrs.',
        },
        {
          const: 4,
          title: 'Mx.',
        },
        {
          const: 5,
          title: 'Other',
        },
      ],
      title: 'Prefix',
      $id: '1210',
    },
    '1211': {
      type: 'string',
      title: 'First name',
      $id: '1211',
      maxLength: 30,
    },
    '1212': {
      type: 'string',
      title: 'Middle initial',
      $id: '1212',
      maxLength: 2,
    },
    '1213': {
      type: 'string',
      title: 'Last name',
      $id: '1213',
      maxLength: 30,
    },
    '1214': {
      type: 'string',
      title: 'Title',
      $id: '1214',
      maxLength: 60,
    },
    '1215': {
      type: 'string',
      title: 'Phone',
      $id: '1215',
    },
    '1216': {
      type: 'string',
      title: 'Fax',
      $id: '1216',
    },
    '1217': {
      type: 'string',
      format: 'email',
      title: 'Email',
      $id: '1217',
    },
    '1218': {
      type: 'string',
      title: 'Profile URL',
      $id: '1218',
      maxLength: 150,
    },
    '1219': {
      type: 'string',
      pattern: '^[0-9]{6}$',
      title: 'High School CEEB code',
      $id: '1219',
      minLength: 6,
      maxLength: 6,
    },
    '1220': {
      type: 'string',
      title: 'Website',
      $id: '1220',
      maxLength: 150,
    },
    '1221': {
      type: 'number',
      title: 'Graduating class size',
      $id: '1221',
      maxLength: 5,
    },
    '1222': {
      type: 'number',
      title: 'Percentage of graduating class attending 2-year college',
      $id: '1222',
      maxLength: 5,
    },
    '1223': {
      type: 'number',
      title: 'Percentage of graduating class attending 4-year college',
      $id: '1223',
      maxLength: 5,
    },
    '1224': {
      type: 'number',
      title: 'Percentage of students who are Hispanic or Latino/a/x',
      $id: '1224',
      maxLength: 5,
    },
    '1225': {
      type: 'number',
      title: 'Percentage of students who are American Indian or Alaska Native',
      $id: '1225',
      maxLength: 5,
    },
    '1226': {
      type: 'number',
      title: 'Percentage of students who are Asian',
      $id: '1226',
      maxLength: 5,
    },
    '1227': {
      type: 'number',
      title: 'Percentage of students who are Black or African American',
      $id: '1227',
      maxLength: 5,
    },
    '1228': {
      type: 'number',
      title: 'Percentage of students who are Native Hawaiian or Other Pacific Islander',
      $id: '1228',
      maxLength: 5,
    },
    '1229': {
      type: 'number',
      title: 'Percentage of students who are White',
      $id: '1229',
      maxLength: 5,
    },
    '1230': {
      type: 'number',
      title: 'Percentage of students who are first-generation college',
      $id: '1230',
      maxLength: 5,
    },
    '1231': {
      type: 'number',
      title: 'Percentage of students who are US Citizens',
      $id: '1231',
      maxLength: 5,
    },
    '1232': {
      type: 'number',
      title: 'Percentage of students who are Non-US Citizens',
      $id: '1232',
      maxLength: 5,
    },
    '1233': {
      type: 'number',
      title: 'Percentage of students who receive free or reduced lunch',
      $id: '1233',
      maxLength: 5,
    },
    '1235': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Rural',
        },
        {
          const: 1,
          title: 'Suburban',
        },
        {
          const: 2,
          title: 'Urban',
        },
      ],
      title: 'School setting',
      $id: '1235',
    },
    '1236': {
      type: 'array',
      uniqueItems: true,
      items: {
        type: 'number',
        anyOf: [
          {
            const: 0,
            title: 'AP',
          },
          {
            const: 1,
            title: 'IB',
          },
          {
            const: 2,
            title: 'Honors',
          },
          {
            const: 3,
            title: 'Cambridge',
          },
        ],
      },
      title: 'Which of the following courses are offered at your school?',
      $id: '1236',
    },
    '1243': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title: 'Are classes taken on a block schedule?',
      $id: '1243',
    },
    '1244': {
      type: 'string',
      format: 'date',
      title: 'Graduation Date',
      $id: '1244',
    },
    '1245': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title: 'Is your school located outside of the United States?',
      $id: '1245',
    },
    '1247': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title:
        "Do you complete applicants' academic ratings on the Common Application School Report?",
      $id: '1247',
    },
    '1248': {
      type: 'string',
      format: 'data-url',
      title: 'Attach your school profile here.',
      $id: '1248',
    },
    '1249': {
      type: 'array',
      uniqueItems: true,
      items: {
        type: 'string',
        anyOf: [
          {
            const: 'Transcript',
            title:
              "By checking this box, I certify that I will upload a PDF of each student's transcript for transmission with the School Report. (Parchment users should also check this box.) I understand that Common App member institutions do not want to receive the School Report transmitted online if the transcript will be mailed. I also understand that if I fail to send the transcript online with the School Report this may cause confusion and processing delays, resulting in an late application decision for the applicant.",
          },
        ],
      },
      title: 'Transcript Affirmation',
      $id: '1249',
    },
    '1250': {
      type: 'array',
      uniqueItems: true,
      items: {
        type: 'string',
        anyOf: [
          {
            const: 'Agreed_Com',
            title:
              'I understand that the Common Application organization may need to periodically contact me regarding updates to the online school forms system. I agree to receive such communications at the email address I have provided above.',
          },
        ],
      },
      title: 'Communication',
      $id: '1250',
    },
    '1832': {
      type: 'number',
      oneOf: [
        {
          const: 0,
          title: 'Yes',
        },
        {
          const: 1,
          title: 'No',
        },
      ],
      title: 'Does your school require students to perform volunteer service?',
      $id: '1832',
    },
    '1955': {
      type: 'string',
      title:
        'Your school may have made adjustments due to community disruptions such as COVID–19 or natural disasters. If you have not already addressed those changes in your uploaded school profile or elsewhere, you can elaborate here. Colleges are especially interested in understanding changes to:<br /><br /><ul><li>Grading scales and policies</li><li>Graduation requirements</li><li>Instructional methods</li><li>Schedules and course offerings</li><li>Testing requirements</li><li>Your academic calendar</li><li>Other extenuating circumstances</li></ul>Your students will have a similar space in their application to share how these events have affected them personally.',
      $id: '1955',
    },
    '1969': {
      type: 'string',
      format: 'date',
      title: 'Approximately when are mid-year grades typically available?',
      $id: '1969',
    },
    'Personal Details': {
      type: 'object',
      properties: {},
    },
    'School Details': {
      type: 'object',
      properties: {},
    },
    'School Profile': {
      type: 'object',
      properties: {},
    },
    Certifications: {
      type: 'object',
      properties: {},
    },
  },
  required: [
    '1211',
    '1213',
    '1214',
    '1215',
    '1217',
    '1219',
    '1221',
    '1243',
    '1244',
    '1245',
    '1247',
    '1249',
    '1250',
    '1832',
  ],
  allOf: [
    {
      if: {
        properties: {
          '1236': {
            contains: {
              const: 0,
            },
          },
        },
      },
      then: {
        properties: {
          '1237': {
            type: 'integer',
            title: 'Number of AP courses offered',
            $id: '1237',
            maxLength: 3,
          },
          '1238': {
            type: 'integer',
            title: 'Maximum number of AP courses a student can take',
            $id: '1238',
            maxLength: 3,
          },
        },
        required: [],
      },
    },
    {
      if: {
        properties: {
          '1236': {
            contains: {
              const: 1,
            },
          },
        },
      },
      then: {
        properties: {
          '1239': {
            type: 'integer',
            title: 'Number of IB courses offered',
            $id: '1239',
            maxLength: 3,
          },
          '1240': {
            type: 'integer',
            title: 'Maximum number of IB courses a student can take',
            $id: '1240',
            maxLength: 3,
          },
        },
        required: [],
      },
    },
    {
      if: {
        properties: {
          '1236': {
            contains: {
              const: 2,
            },
          },
        },
      },
      then: {
        properties: {
          '1241': {
            type: 'integer',
            title: 'Number of Honors courses offered',
            $id: '1241',
            maxLength: 3,
          },
          '1242': {
            type: 'integer',
            title: 'Maximum number of Honors courses a student can take',
            $id: '1242',
            maxLength: 3,
          },
        },
        required: [],
      },
    },
    {
      if: {
        properties: {
          '1245': {
            const: 0,
          },
        },
      },
      then: {
        properties: {
          '1246': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'Yes',
              },
              {
                const: 1,
                title: 'No',
              },
            ],
            title: 'Do you use an AP curriculum?',
            $id: '1246',
          },
        },
        required: ['1246'],
      },
    },
    {
      if: {
        properties: {
          '1832': {
            const: 0,
          },
        },
      },
      then: {
        properties: {
          '1833': {
            type: 'string',
            title: 'Please describe what is required',
            $id: '1833',
            maxLength: 150,
          },
        },
        required: [],
      },
    },
    {
      if: {
        properties: {
          '1236': {
            contains: {
              const: 3,
            },
          },
        },
      },
      then: {
        properties: {
          '1972': {
            type: 'integer',
            title: 'Number of Cambridge courses offered',
            $id: '1972',
            maxLength: 3,
          },
          '1973': {
            type: 'integer',
            title: 'Maximum number of Cambridge courses a student can take',
            $id: '1973',
            maxLength: 3,
          },
        },
        required: [],
      },
    },
    {
      if: {
        properties: {
          '1210': {
            const: 5,
          },
        },
      },
      then: {
        properties: {
          '2065': {
            type: 'string',
            title: 'Other prefix',
            $id: '2065',
            maxLength: 24,
          },
        },
        required: ['2065'],
      },
    },
  ],
};

export const counselorProfileUiSchema = {
  '1215': {
    'ui:widget': 'PhoneWidget',
  },
  '1216': {
    'ui:widget': 'PhoneWidget',
  },
  '1235': {
    'ui:widget': 'radio',
  },
  '1236': {
    'ui:widget': 'checkboxes',
  },
  '1243': {
    'ui:widget': 'radio',
  },
  '1244': {
    'ui:options': {
      yearsRange: ['1952', '2028'],
    },
  },
  '1245': {
    'ui:widget': 'radio',
  },
  '1246': {
    'ui:widget': 'radio',
  },
  '1247': {
    'ui:widget': 'radio',
  },
  '1248': {
    'ui:options': {
      accept: '.pdf',
    },
  },
  '1249': {
    'ui:widget': 'checkboxes',
  },
  '1250': {
    'ui:widget': 'checkboxes',
  },
  '1955': {
    'ui:widget': 'textarea',
  },
  '1969': {
    'ui:options': {
      yearsRange: ['2023', '2024'],
    },
  },
  'ui:order': [
    'Personal Details',
    '1210',
    '2065',
    '1211',
    '1212',
    '1213',
    '1214',
    '1215',
    '1216',
    '1217',
    '1218',
    'School Details',
    '1955',
    '1219',
    '1220',
    'School Profile',
    '1969',
    '1221',
    '1222',
    '1223',
    '1224',
    '1225',
    '1226',
    '1227',
    '1228',
    '1229',
    '1230',
    '1231',
    '1232',
    '1233',
    '1234',
    '1235',
    '1236',
    '1237',
    '1238',
    '1239',
    '1240',
    '1241',
    '1242',
    '1972',
    '1973',
    '1243',
    '1244',
    '1245',
    '1246',
    '1247',
    '1832',
    '1833',
    '1248',
    'Certifications',
    '1249',
    '1250',
  ],
};

export const counselorInitialValues = {
  '1210': null,
  '1236': [],
  '1245': '',
  '1832': '',
};

// raw questions data in case we need it

export const counselorProfileRawQuestions: CommonAppRawQuestions = {
  '1210': {
    sectionName: 'Personal Details',
    id: '1210',
    label: 'Prefix',
    type: 'SingleSelectDropdown',
    name: 'Counselor title',
    format: null,
    choiceGroup: 'Prefix',
    orderSeq: '10',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1211': {
    sectionName: 'Personal Details',
    id: '1211',
    label: 'First name',
    type: 'Short',
    name: 'Counselor first name',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1212': {
    sectionName: 'Personal Details',
    id: '1212',
    label: 'Middle initial',
    type: 'Short',
    name: 'Counselor MI',
    format: null,
    choiceGroup: null,
    orderSeq: '30',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '2',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1213': {
    sectionName: 'Personal Details',
    id: '1213',
    label: 'Last name',
    type: 'Short',
    name: 'Counselor last name',
    format: null,
    choiceGroup: null,
    orderSeq: '40',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1214': {
    sectionName: 'Personal Details',
    id: '1214',
    label: 'Title',
    type: 'Short',
    name: 'Counselor position',
    format: null,
    choiceGroup: null,
    orderSeq: '50',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '60',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1215': {
    sectionName: 'Personal Details',
    id: '1215',
    label: 'Phone',
    type: 'Phone',
    name: 'Counselor phone',
    format: 'Phone Validations',
    choiceGroup: null,
    orderSeq: '60',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1216': {
    sectionName: 'Personal Details',
    id: '1216',
    label: 'Fax',
    type: 'Phone',
    name: 'Counselor fax',
    format: 'Phone Validations',
    choiceGroup: null,
    orderSeq: '70',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1217': {
    sectionName: 'Personal Details',
    id: '1217',
    label: 'Email',
    type: 'Email',
    name: 'Counselor email',
    format: "(must include '@' in response)",
    choiceGroup: null,
    orderSeq: '80',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1218': {
    sectionName: 'Personal Details',
    id: '1218',
    label: 'Profile URL',
    type: 'Short',
    name: 'Profile URL',
    format: null,
    choiceGroup: null,
    orderSeq: '90',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '150',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1219': {
    sectionName: 'School Details',
    id: '1219',
    label: 'High School CEEB code',
    type: '6 digit High School CEEB code',
    name: 'Counselor School lookup',
    format: '######',
    choiceGroup: null,
    orderSeq: '10',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1220': {
    sectionName: 'School Details',
    id: '1220',
    label: 'Website',
    type: 'Short',
    name: 'Website',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '150',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1221': {
    sectionName: 'School Profile',
    id: '1221',
    label: 'Graduating class size',
    type: 'Short',
    name: 'Class size',
    format: null,
    choiceGroup: null,
    orderSeq: '10',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1222': {
    sectionName: 'School Profile',
    id: '1222',
    label: 'Percentage of graduating class attending 2-year college',
    type: 'Short',
    name: 'Two-year college percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1223': {
    sectionName: 'School Profile',
    id: '1223',
    label: 'Percentage of graduating class attending 4-year college',
    type: 'Short',
    name: 'Four-year college percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '30',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1224': {
    sectionName: 'School Profile',
    id: '1224',
    label: 'Percentage of students who are Hispanic or Latino/a/x',
    type: 'Short',
    name: 'Latino student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '40',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1225': {
    sectionName: 'School Profile',
    id: '1225',
    label: 'Percentage of students who are American Indian or Alaska Native',
    type: 'Short',
    name: 'American Indian student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '50',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1226': {
    sectionName: 'School Profile',
    id: '1226',
    label: 'Percentage of students who are Asian',
    type: 'Short',
    name: 'Asian student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '60',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1227': {
    sectionName: 'School Profile',
    id: '1227',
    label: 'Percentage of students who are Black or African American',
    type: 'Short',
    name: 'African American student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '70',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1228': {
    sectionName: 'School Profile',
    id: '1228',
    label: 'Percentage of students who are Native Hawaiian or Other Pacific Islander',
    type: 'Short',
    name: 'Native student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '80',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1229': {
    sectionName: 'School Profile',
    id: '1229',
    label: 'Percentage of students who are White',
    type: 'Short',
    name: 'White student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '90',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1230': {
    sectionName: 'School Profile',
    id: '1230',
    label: 'Percentage of students who are first-generation college',
    type: 'Short',
    name: 'First gen student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '100',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1231': {
    sectionName: 'School Profile',
    id: '1231',
    label: 'Percentage of students who are US Citizens',
    type: 'Short',
    name: 'US citizen student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '110',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1232': {
    sectionName: 'School Profile',
    id: '1232',
    label: 'Percentage of students who are Non-US Citizens',
    type: 'Short',
    name: 'Non US citizen student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '120',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1233': {
    sectionName: 'School Profile',
    id: '1233',
    label: 'Percentage of students who receive free or reduced lunch',
    type: 'Short',
    name: 'Free lunch student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '130',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1234': {
    sectionName: 'School Profile',
    id: '1234',
    label: 'Percentage of students who receive financial aid',
    type: 'Short',
    name: 'Financial aid student percentage',
    format: null,
    choiceGroup: null,
    orderSeq: '140',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'Financial aid number shown',
    dataType: 'Double',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '5',
    allowedCharacters: '[^0-9.]',
    validationPattern: '^[0-9]*?.[0-9]*$',
    errorMessage:
      'Sorry, we can accept only numbers and decimals, please provide a different answer.',
    groupValidation: null,
  },
  '1235': {
    sectionName: 'School Profile',
    id: '1235',
    label: 'School setting',
    type: 'Radio',
    name: 'School setting',
    format: null,
    choiceGroup: 'School setting',
    orderSeq: '150',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1236': {
    sectionName: 'School Profile',
    id: '1236',
    label: 'Which of the following courses are offered at your school?',
    type: 'Checkbox',
    name: 'Courses offered',
    format: null,
    choiceGroup: 'Courses offered',
    orderSeq: '160',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1237': {
    sectionName: 'School Profile',
    id: '1237',
    label: 'Number of AP courses offered',
    type: 'Short',
    name: 'AP course offering number',
    format: null,
    choiceGroup: null,
    orderSeq: '170',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'AP course details shown',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '3',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1238': {
    sectionName: 'School Profile',
    id: '1238',
    label: 'Maximum number of AP courses a student can take',
    type: 'Short',
    name: 'AP course limit',
    format: null,
    choiceGroup: null,
    orderSeq: '180',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'AP course details shown',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '3',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1239': {
    sectionName: 'School Profile',
    id: '1239',
    label: 'Number of IB courses offered',
    type: 'Short',
    name: 'IB course offering number',
    format: null,
    choiceGroup: null,
    orderSeq: '190',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'IB course details shown',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '3',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1240': {
    sectionName: 'School Profile',
    id: '1240',
    label: 'Maximum number of IB courses a student can take',
    type: 'Short',
    name: 'IB course limit',
    format: null,
    choiceGroup: null,
    orderSeq: '200',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'IB course details shown',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '3',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1241': {
    sectionName: 'School Profile',
    id: '1241',
    label: 'Number of Honors courses offered',
    type: 'Short',
    name: 'Honors course offering number',
    format: null,
    choiceGroup: null,
    orderSeq: '210',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'Honors course details shown',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '3',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1242': {
    sectionName: 'School Profile',
    id: '1242',
    label: 'Maximum number of Honors courses a student can take',
    type: 'Short',
    name: 'Honors course limit',
    format: null,
    choiceGroup: null,
    orderSeq: '220',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'Honors course details shown',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '3',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1243': {
    sectionName: 'School Profile',
    id: '1243',
    label: 'Are classes taken on a block schedule?',
    type: 'Radio',
    name: 'Block schedule',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '230',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1244': {
    sectionName: 'School Profile',
    id: '1244',
    label: 'Graduation Date',
    type: 'Date',
    name: 'Graduation date',
    format: 'MM/DD/YYYY',
    choiceGroup: null,
    orderSeq: '240',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Date',
    minWordsYear: '1952',
    maxWordsYearKb: '2028',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1245': {
    sectionName: 'School Profile',
    id: '1245',
    label: 'Is your school located outside of the United States?',
    type: 'Radio',
    name: 'International school',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '250',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1246': {
    sectionName: 'School Profile',
    id: '1246',
    label: 'Do you use an AP curriculum?',
    type: 'Radio',
    name: 'Use AP curriculum',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '260',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'AP curriculum question',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1247': {
    sectionName: 'School Profile',
    id: '1247',
    label: "Do you complete applicants' academic ratings on the Common Application School Report?",
    type: 'Radio',
    name: 'Counselor Academic ratings',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '270',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1248': {
    sectionName: 'School Profile',
    id: '1248',
    label: 'Attach your school profile here.',
    type: 'Upload',
    name: 'School profile upload',
    format: null,
    choiceGroup: null,
    orderSeq: '300',
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '2000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1249': {
    sectionName: 'Certifications',
    id: '1249',
    label: 'Transcript Affirmation',
    type: 'Checkbox',
    name: 'Certification 1',
    format: null,
    choiceGroup: 'Transcript Affirmation',
    orderSeq: '10',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1250': {
    sectionName: 'Certifications',
    id: '1250',
    label: 'Communication',
    type: 'Checkbox',
    name: 'Certification 2',
    format: null,
    choiceGroup: 'Communication',
    orderSeq: '20',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1832': {
    sectionName: 'School Profile',
    id: '1832',
    label: 'Does your school require students to perform volunteer service?',
    type: 'SingleSelectDropdown',
    name: 'Service Hours',
    format: null,
    choiceGroup: 'Yes No',
    orderSeq: '280',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1833': {
    sectionName: 'School Profile',
    id: '1833',
    label: 'Please describe what is required',
    type: 'Short',
    name: 'Service Hours Description',
    format: null,
    choiceGroup: null,
    orderSeq: '290',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'Service Hours Description Optional',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '150',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1955': {
    sectionName: 'School Details',
    id: '1955',
    label:
      'Your school may have made adjustments due to community disruptions such as COVID–19 or natural disasters. If you have not already addressed those changes in your uploaded school profile or elsewhere, you can elaborate here. Colleges are especially interested in understanding changes to:<br /><br /><ul><li>Grading scales and policies</li><li>Graduation requirements</li><li>Instructional methods</li><li>Schedules and course offerings</li><li>Testing requirements</li><li>Your academic calendar</li><li>Other extenuating circumstances</li></ul>Your students will have a similar space in their application to share how these events have affected them personally.',
    type: 'Long',
    name: 'Counselor community disruption',
    format: null,
    choiceGroup: null,
    orderSeq: null,
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '500',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1969': {
    sectionName: 'School Profile',
    id: '1969',
    label: 'Approximately when are mid-year grades typically available?',
    type: 'Date',
    name: 'Expected MR Date',
    format: 'MM/DD/YYYY',
    choiceGroup: null,
    orderSeq: null,
    defaultState: 'Optional',
    triggeredState: null,
    requirementRule: null,
    dataType: 'Date',
    minWordsYear: '2023',
    maxWordsYearKb: '2024',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1972': {
    sectionName: 'School Profile',
    id: '1972',
    label: 'Number of Cambridge courses offered',
    type: 'Short',
    name: 'Cambridge course offering number',
    format: null,
    choiceGroup: null,
    orderSeq: '225',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'Cambridge course details shown',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '3',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '1973': {
    sectionName: 'School Profile',
    id: '1973',
    label: 'Maximum number of Cambridge courses a student can take',
    type: 'Short',
    name: 'Cambridge course limit',
    format: null,
    choiceGroup: null,
    orderSeq: '226',
    defaultState: 'Hidden',
    triggeredState: 'Optional',
    requirementRule: 'Cambridge course details shown',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '3',
    allowedCharacters: '[^0-9]',
    validationPattern: null,
    errorMessage:
      'Sorry, we can accept only digits for this answer, please provide a different answer.',
    groupValidation: null,
  },
  '2065': {
    sectionName: 'Personal Details',
    id: '2065',
    label: 'Other prefix',
    type: 'Short',
    name: 'Counselor Other Prefix',
    format: null,
    choiceGroup: null,
    orderSeq: '15',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Counselor Other Prefix rule',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '24',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
};
