import { RJSFSchema, UiSchema } from '@rjsf/utils';

import { CommonAppRawQuestions } from '../forms';

export const teQuestionsSchema: RJSFSchema = {
  type: 'object',
  $defs: {},
  properties: {
    '1426': {
      type: 'number',
      oneOf: [
        {
          const: 6,
          title: 'Computer Science',
        },
        {
          const: 1,
          title: 'English',
        },
        {
          const: 0,
          title: 'Math',
        },
        {
          const: 2,
          title: 'Science',
        },
        {
          const: 4,
          title: 'Social Studies',
        },
        {
          const: 3,
          title: 'World Language',
        },
        {
          const: 5,
          title: 'Other',
        },
      ],
      title: 'Subject Area',
      $id: '1426',
    },
    '1443': {
      type: 'string',
      title:
        '<b>You can submit this form only one time for this applicant. Your responses and all accompanying documents will be shared with all of the colleges to which the applicant applies. For that reason, you should not tailor this form for any particular institution. Once you submit, you will be unable to modify these forms or documents in any way.</b><br/><br/>How long have you known this student and in what context?',
      $id: '1443',
    },
    '1444': {
      type: 'string',
      title: 'What are the first words that come to your mind to describe this student?',
      $id: '1444',
    },
    '1445': {
      type: 'array',
      uniqueItems: true,
      items: {
        type: 'number',
        anyOf: [
          {
            const: 0,
            title: '9th',
          },
          {
            const: 1,
            title: '10th',
          },
          {
            const: 2,
            title: '11th',
          },
          {
            const: 3,
            title: '12th',
          },
          {
            const: 4,
            title: 'Other',
          },
        ],
      },
      title: 'In which grade level(s) was the student enrolled when you taught him/her?',
      $id: '1445',
    },
    '1447': {
      type: 'string',
      title:
        'List the courses in which you have taught this student, including the level of course difficulty (AP, IB, accelerated, Cambridge, honors, elective; 100-level, 200-level; etc.).',
      $id: '1447',
    },
    '1448': {
      type: 'string',
      format: 'data-url',
      title:
        'Please upload a document describing what you think is important about this student, including a description of academic and personal characteristics, as demonstrated in your classroom. We welcome information that will help us to differentiate this student',
      $id: '1448',
    },
    'Subject Area': {
      type: 'object',
      properties: {},
    },
    Ratings: {
      type: 'object',
      properties: {},
    },
    'Written Evaluation': {
      type: 'object',
      properties: {},
    },
  },
  required: ['1426', '1443', '1444', '1445', '1447', '1448'],
  allOf: [
    {
      if: {
        properties: {
          '1397': {
            const: 0,
          },
        },
      },
      then: {
        properties: {
          '1427': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Academic Achievement',
            $id: '1427',
          },
          '1428': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Intellectual Promise',
            $id: '1428',
          },
          '1429': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Quality of Writing',
            $id: '1429',
          },
          '1430': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Creative Thought',
            $id: '1430',
          },
          '1431': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Productive discussion',
            $id: '1431',
          },
          '1432': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Faculty Respect',
            $id: '1432',
          },
          '1433': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Disciplined Habits',
            $id: '1433',
          },
          '1434': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Maturity',
            $id: '1434',
          },
          '1435': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Motivation',
            $id: '1435',
          },
          '1436': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Leadership',
            $id: '1436',
          },
          '1437': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Integrity',
            $id: '1437',
          },
          '1438': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Reaction to setbacks',
            $id: '1438',
          },
          '1439': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Concern for others',
            $id: '1439',
          },
          '1440': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Self confidence',
            $id: '1440',
          },
          '1441': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Initiative',
            $id: '1441',
          },
          '1442': {
            type: 'number',
            oneOf: [
              {
                const: 0,
                title: 'No basis',
              },
              {
                const: 1,
                title: 'Below Average',
              },
              {
                const: 2,
                title: 'Average',
              },
              {
                const: 3,
                title: 'Good (above average)',
              },
              {
                const: 4,
                title: 'Very good (well above average)',
              },
              {
                const: 5,
                title: 'Excellent (top 10%)',
              },
              {
                const: 6,
                title: 'Outstanding (top 5%)',
              },
              {
                const: 7,
                title: 'One of the top few encountered in my career',
              },
            ],
            title: 'Overall Evaluation',
            $id: '1442',
          },
        },
        required: [
          '1427',
          '1428',
          '1429',
          '1430',
          '1431',
          '1432',
          '1433',
          '1434',
          '1435',
          '1436',
          '1437',
          '1438',
          '1439',
          '1440',
          '1441',
          '1442',
        ],
      },
    },
    {
      if: {
        properties: {
          '1445': {
            contains: {
              const: 4,
            },
          },
        },
      },
      then: {
        properties: {
          '1446': {
            type: 'string',
            title: 'TE Grade Level Other',
            $id: '1446',
            maxLength: 30,
          },
        },
        required: ['1446'],
      },
    },
  ],
};

export const teQuestionsUISchema: { [key: string]: UiSchema } = {
  '1427': {
    'ui:widget': 'radio',
  },
  '1428': {
    'ui:widget': 'radio',
  },
  '1429': {
    'ui:widget': 'radio',
  },
  '1430': {
    'ui:widget': 'radio',
  },
  '1431': {
    'ui:widget': 'radio',
  },
  '1432': {
    'ui:widget': 'radio',
  },
  '1433': {
    'ui:widget': 'radio',
  },
  '1434': {
    'ui:widget': 'radio',
  },
  '1435': {
    'ui:widget': 'radio',
  },
  '1436': {
    'ui:widget': 'radio',
  },
  '1437': {
    'ui:widget': 'radio',
  },
  '1438': {
    'ui:widget': 'radio',
  },
  '1439': {
    'ui:widget': 'radio',
  },
  '1440': {
    'ui:widget': 'radio',
  },
  '1441': {
    'ui:widget': 'radio',
  },
  '1442': {
    'ui:widget': 'radio',
  },
  '1443': {
    'ui:widget': 'textarea',
  },
  '1444': {
    'ui:widget': 'textarea',
  },
  '1445': {
    'ui:widget': 'checkboxes',
  },
  '1447': {
    'ui:widget': 'textarea',
  },
  '1448': {
    'ui:options': {
      accept: '.pdf',
    },
  },
  'ui:order': [
    'Subject Area',
    '1397',
    '1426',
    'Ratings',
    '1427',
    '1428',
    '1429',
    '1430',
    '1431',
    '1432',
    '1433',
    '1434',
    '1435',
    '1436',
    '1437',
    '1438',
    '1439',
    '1440',
    '1441',
    '1442',
    'Written Evaluation',
    '1443',
    '1444',
    '1445',
    '1446',
    '1447',
    '1448',
  ],
};
export const teQuestionsInitialData = {
  '1445': [],
};

export const teacherEvaluationRawQuestions: CommonAppRawQuestions = {
  '1426': {
    sectionName: 'Subject Area',
    id: '1426',
    label: 'Subject Area',
    type: 'SingleSelectDropdown',
    name: 'TE Subject Area',
    format: null,
    choiceGroup: 'Subject Area',
    orderSeq: '5',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1427': {
    sectionName: 'Ratings',
    id: '1427',
    label: 'Academic Achievement',
    type: 'Radio',
    name: 'TE Academic Achievement',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '5',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1428': {
    sectionName: 'Ratings',
    id: '1428',
    label: 'Intellectual Promise',
    type: 'Radio',
    name: 'TE Intellectual Promise',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '10',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1429': {
    sectionName: 'Ratings',
    id: '1429',
    label: 'Quality of Writing',
    type: 'Radio',
    name: 'TE Quality of Writing',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '15',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1430': {
    sectionName: 'Ratings',
    id: '1430',
    label: 'Creative Thought',
    type: 'Radio',
    name: 'TE Creative Thought',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '20',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1431': {
    sectionName: 'Ratings',
    id: '1431',
    label: 'Productive discussion',
    type: 'Radio',
    name: 'TE Productive discussion',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '25',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1432': {
    sectionName: 'Ratings',
    id: '1432',
    label: 'Faculty Respect',
    type: 'Radio',
    name: 'TE Faculty Respect',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '30',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1433': {
    sectionName: 'Ratings',
    id: '1433',
    label: 'Disciplined Habits',
    type: 'Radio',
    name: 'TE Disciplined Habits',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '35',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1434': {
    sectionName: 'Ratings',
    id: '1434',
    label: 'Maturity',
    type: 'Radio',
    name: 'TE Maturity',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '40',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1435': {
    sectionName: 'Ratings',
    id: '1435',
    label: 'Motivation',
    type: 'Radio',
    name: 'TE Motivation',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '45',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1436': {
    sectionName: 'Ratings',
    id: '1436',
    label: 'Leadership',
    type: 'Radio',
    name: 'TE Leadership',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '50',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1437': {
    sectionName: 'Ratings',
    id: '1437',
    label: 'Integrity',
    type: 'Radio',
    name: 'TE Integrity',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '55',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1438': {
    sectionName: 'Ratings',
    id: '1438',
    label: 'Reaction to setbacks',
    type: 'Radio',
    name: 'TE Reaction to setbacks',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '60',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1439': {
    sectionName: 'Ratings',
    id: '1439',
    label: 'Concern for others',
    type: 'Radio',
    name: 'TE Concern for others',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '65',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1440': {
    sectionName: 'Ratings',
    id: '1440',
    label: 'Self confidence',
    type: 'Radio',
    name: 'TE Self confidence',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '70',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1441': {
    sectionName: 'Ratings',
    id: '1441',
    label: 'Initiative',
    type: 'Radio',
    name: 'TE Initiative',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '75',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1442': {
    sectionName: 'Ratings',
    id: '1442',
    label: 'Overall Evaluation',
    type: 'Radio',
    name: 'TE Overall',
    format: null,
    choiceGroup: 'Ratings',
    orderSeq: '80',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Ratings Required',
    dataType: 'Integer',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1443': {
    sectionName: 'Written Evaluation',
    id: '1443',
    label:
      '<b>You can submit this form only one time for this applicant. Your responses and all accompanying documents will be shared with all of the colleges to which the applicant applies. For that reason, you should not tailor this form for any particular institution. Once you submit, you will be unable to modify these forms or documents in any way.</b><br/><br/>How long have you known this student and in what context?',
    type: 'Long',
    name: 'TE How long known',
    format: null,
    choiceGroup: null,
    orderSeq: '5',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '1000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1444': {
    sectionName: 'Written Evaluation',
    id: '1444',
    label: 'What are the first words that come to your mind to describe this student?',
    type: 'Long',
    name: 'TE First words',
    format: null,
    choiceGroup: null,
    orderSeq: '10',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '1000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1445': {
    sectionName: 'Written Evaluation',
    id: '1445',
    label: 'In which grade level(s) was the student enrolled when you taught him/her?',
    type: 'Checkbox',
    name: 'TE Grade level',
    format: null,
    choiceGroup: 'Grade Level',
    orderSeq: '15',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1446': {
    sectionName: 'Written Evaluation',
    id: '1446',
    label: 'TE Grade Level Other',
    type: 'Short',
    name: 'TE Grade Level Other',
    format: null,
    choiceGroup: null,
    orderSeq: '20',
    defaultState: 'Hidden',
    triggeredState: 'Required',
    requirementRule: 'Other Required',
    dataType: 'String',
    minWordsYear: null,
    maxWordsYearKb: null,
    maxCharacters: '30',
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1447': {
    sectionName: 'Written Evaluation',
    id: '1447',
    label:
      'List the courses in which you have taught this student, including the level of course difficulty (AP, IB, accelerated, Cambridge, honors, elective; 100-level, 200-level; etc.).',
    type: 'Long',
    name: 'TE Courses',
    format: null,
    choiceGroup: null,
    orderSeq: '25',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '1000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
  '1448': {
    sectionName: 'Written Evaluation',
    id: '1448',
    label:
      'Please upload a document describing what you think is important about this student, including a description of academic and personal characteristics, as demonstrated in your classroom. We welcome information that will help us to differentiate this student',
    type: 'Upload',
    name: 'TE Short Evaluation',
    format: null,
    choiceGroup: null,
    orderSeq: '30',
    defaultState: 'Required',
    triggeredState: null,
    requirementRule: null,
    dataType: null,
    minWordsYear: null,
    maxWordsYearKb: '2000',
    maxCharacters: null,
    allowedCharacters: null,
    validationPattern: null,
    errorMessage: null,
    groupValidation: null,
  },
};
